import React from 'react';
import { EvaluationResult, PracticeSession, UserProfile } from '../types';
import {
  Award,
  CheckCircle2,
  AlertTriangle,
  BookOpen,
  Volume2,
  Sparkles,
  ArrowRight,
  RefreshCw,
  TrendingUp,
  LayoutDashboard,
  HelpCircle,
  Lightbulb,
  FileText,
  Target,
  Share2
} from 'lucide-react';

interface EvaluationPageProps {
  user: UserProfile;
  session: PracticeSession;
  onPracticeAgain: () => void;
  onViewProgress: () => void;
  onBackToDashboard: () => void;
}

export const EvaluationPage: React.FC<EvaluationPageProps> = ({
  user,
  session,
  onPracticeAgain,
  onViewProgress,
  onBackToDashboard,
}) => {
  const { evaluation } = session;
  const criteria = evaluation.criteria;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Official AI Estimated Score Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 via-indigo-600 to-pink-500 p-6 sm:p-10 text-white shadow-xl shadow-indigo-200">
        <div className="absolute -top-10 -right-10 w-64 h-64 bg-white/10 rounded-full blur-2xl pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="px-3 py-1 rounded-full bg-white/20 backdrop-blur-md text-white text-xs font-black">
                {session.part}
              </span>
              <span className="px-2.5 py-1 rounded-full bg-amber-400/30 text-amber-200 text-xs font-bold">
                {session.difficulty} Difficulty
              </span>
              <span className="text-xs text-indigo-100">
                {new Date(session.date).toLocaleDateString()}
              </span>
            </div>

            <h1 className="text-2xl sm:text-4xl font-black tracking-tight">
              Evaluation & Examiner Feedback
            </h1>

            <p className="text-sm sm:text-base text-indigo-100 max-w-xl">
              Topic: <span className="font-bold text-white">"{session.topic}"</span>
            </p>
          </div>

          {/* Big Estimated Band Score Pill */}
          <div className="bg-white/15 backdrop-blur-md p-5 sm:p-6 rounded-3xl border border-white/25 text-center flex flex-col items-center justify-center shrink-0 min-w-[170px]">
            <span className="text-[11px] font-black uppercase tracking-wider text-indigo-200">
              AI Estimated Band
            </span>
            <div className="flex items-baseline gap-1 my-1">
              <span className="text-4xl sm:text-5xl font-black text-white">
                {evaluation.overallBand.toFixed(1)}
              </span>
              <span className="text-lg font-bold text-indigo-200">/ 9.0</span>
            </div>
            <span className="text-xs font-bold text-emerald-300 bg-emerald-950/40 px-2.5 py-0.5 rounded-full">
              Target Band {user.targetBand.toFixed(1)}
            </span>
          </div>
        </div>

        {/* Disclaimer Notice: Important requirement */}
        <div className="mt-6 pt-4 border-t border-white/15 flex items-center gap-2 text-xs text-indigo-100/90">
          <HelpCircle className="w-4 h-4 shrink-0 text-amber-300" />
          <span>
            <strong>AI Estimated Score:</strong> This evaluation is generated by AI IELTS examiner models for formative practice and self-study, not an official test result from IDP or the British Council.
          </span>
        </div>
      </div>

      {/* CANDIDATE'S EXACT SPOKEN RESPONSE & AUDIO PLAYBACK */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-100 shadow-md space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2 flex-wrap">
            <FileText className="w-5 h-5 text-indigo-600" />
            <h3 className="text-base sm:text-lg font-black text-slate-900">
              Candidate's Exact Spoken Response
            </h3>
            <span className="text-xs bg-indigo-50 text-indigo-700 font-bold px-3 py-1 rounded-full">
              {session.transcript.trim().split(/\s+/).filter(Boolean).length} words recorded
            </span>
          </div>

          {session.audioUrl && (
            <div className="flex items-center gap-2 bg-slate-50 px-3 py-1.5 rounded-2xl border border-slate-200/70">
              <Volume2 className="w-4 h-4 text-indigo-600" />
              <span className="text-xs font-bold text-slate-700">Listen back:</span>
              <audio controls src={session.audioUrl} className="h-8 max-w-[200px]" />
            </div>
          )}
        </div>

        <div className="p-4 sm:p-5 rounded-2xl bg-slate-50/80 border border-slate-200/80">
          <p className="text-sm sm:text-base text-slate-800 leading-relaxed font-medium">
            "{session.transcript}"
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs text-slate-500">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>
            <strong>Real Transcript Grounding:</strong> All feedback, mistakes, and vocabulary recommendations below are evaluated exclusively on these words.
          </span>
        </div>
      </div>

      {/* 4 IELTS ASSESSMENT CRITERIA CARDS */}
      <div>
        <div className="mb-4">
          <h2 className="text-xl font-black text-slate-900 tracking-tight">
            IELTS Criteria Breakdown
          </h2>
          <p className="text-xs sm:text-sm text-slate-500">
            Official 4-part assessment framework calibrated to IELTS Band descriptors
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* 1. Fluency and Coherence */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-xs flex flex-col justify-between hover:shadow-md transition-shadow">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-extrabold text-blue-700 uppercase tracking-wider">
                  Fluency & Coherence
                </span>
                <span className="text-xl font-black text-blue-700 bg-blue-50 px-2.5 py-0.5 rounded-xl">
                  {criteria.fluencyCoherence.band.toFixed(1)}
                </span>
              </div>
              <p className="text-xs text-slate-600 leading-relaxed mt-2">
                {criteria.fluencyCoherence.feedback}
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-slate-100 text-[11px] text-blue-600 font-bold flex items-center gap-1">
              <span>• Cohesive devices & flow</span>
            </div>
          </div>

          {/* 2. Lexical Resource */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-xs flex flex-col justify-between hover:shadow-md transition-shadow">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-extrabold text-purple-700 uppercase tracking-wider">
                  Lexical Resource
                </span>
                <span className="text-xl font-black text-purple-700 bg-purple-50 px-2.5 py-0.5 rounded-xl">
                  {criteria.lexicalResource.band.toFixed(1)}
                </span>
              </div>
              <p className="text-xs text-slate-600 leading-relaxed mt-2">
                {criteria.lexicalResource.feedback}
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-slate-100 text-[11px] text-purple-600 font-bold flex items-center gap-1">
              <span>• Vocabulary range & precision</span>
            </div>
          </div>

          {/* 3. Grammatical Range and Accuracy */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-xs flex flex-col justify-between hover:shadow-md transition-shadow">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-extrabold text-pink-700 uppercase tracking-wider">
                  Grammar Range & Acc.
                </span>
                <span className="text-xl font-black text-pink-700 bg-pink-50 px-2.5 py-0.5 rounded-xl">
                  {criteria.grammaticalRangeAccuracy.band.toFixed(1)}
                </span>
              </div>
              <p className="text-xs text-slate-600 leading-relaxed mt-2">
                {criteria.grammaticalRangeAccuracy.feedback}
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-slate-100 text-[11px] text-pink-600 font-bold flex items-center gap-1">
              <span>• Complex sentence variety</span>
            </div>
          </div>

          {/* 4. Pronunciation */}
          <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-xs flex flex-col justify-between hover:shadow-md transition-shadow">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-extrabold text-amber-700 uppercase tracking-wider">
                  Pronunciation
                </span>
                <span className="text-xl font-black text-amber-700 bg-amber-50 px-2.5 py-0.5 rounded-xl">
                  {criteria.pronunciation.band.toFixed(1)}
                </span>
              </div>
              <p className="text-xs text-slate-600 leading-relaxed mt-2">
                {criteria.pronunciation.feedback}
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-slate-100 text-[11px] text-amber-600 font-bold flex items-center gap-1">
              <span>• Intonation & clarity</span>
            </div>
          </div>
        </div>
      </div>

      {/* STRENGTHS & ROOM FOR IMPROVEMENT */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* What You Did Well */}
        <div className="bg-white rounded-3xl p-6 sm:p-7 border border-slate-100 shadow-xs">
          <div className="flex items-center gap-2 text-emerald-700 mb-4">
            <CheckCircle2 className="w-5 h-5 text-emerald-600" />
            <h3 className="font-extrabold text-base text-slate-900">
              What You Did Well (Strengths)
            </h3>
          </div>
          <ul className="space-y-3">
            {evaluation.strengths.map((str, idx) => (
              <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700 leading-relaxed">
                <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                  ✓
                </span>
                <span>{str}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Room for Improvement */}
        <div className="bg-white rounded-3xl p-6 sm:p-7 border border-slate-100 shadow-xs">
          <div className="flex items-center gap-2 text-amber-700 mb-4">
            <Target className="w-5 h-5 text-amber-600" />
            <h3 className="font-extrabold text-base text-slate-900">
              Key Areas for Improvement
            </h3>
          </div>
          <ul className="space-y-3">
            {evaluation.roomForImprovement.map((imp, idx) => (
              <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700 leading-relaxed">
                <span className="w-5 h-5 rounded-full bg-amber-100 text-amber-800 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                  !
                </span>
                <span>{imp}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* SPECIFIC MISTAKES & CORRECTIONS */}
      {evaluation.mistakes && evaluation.mistakes.length > 0 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-100 shadow-xs">
          <div className="flex items-center gap-2 mb-5">
            <AlertTriangle className="w-5 h-5 text-rose-500" />
            <h3 className="font-extrabold text-base sm:text-lg text-slate-900">
              Specific Mistakes from Your Response
            </h3>
          </div>

          <div className="space-y-4">
            {evaluation.mistakes.map((m, idx) => (
              <div
                key={idx}
                className="p-4 sm:p-5 rounded-2xl bg-rose-50/40 border border-rose-100 space-y-2.5"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="space-y-1">
                    <p className="text-xs font-bold text-rose-700 uppercase tracking-wider">Candidate said:</p>
                    <p className="text-sm font-semibold text-slate-800 bg-white/80 p-2.5 rounded-xl border border-rose-200 line-through decoration-rose-400">
                      "{m.original}"
                    </p>
                  </div>
                  <div className="space-y-1">
                    <p className="text-xs font-bold text-emerald-700 uppercase tracking-wider">Examiner correction:</p>
                    <p className="text-sm font-bold text-emerald-900 bg-emerald-50 p-2.5 rounded-xl border border-emerald-200">
                      "{m.correction}"
                    </p>
                  </div>
                </div>
                <p className="text-xs text-slate-600 bg-white/50 p-2.5 rounded-xl border border-slate-100">
                  <span className="font-bold text-slate-700">Why: </span>
                  {m.explanation}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* VOCABULARY ENHANCEMENT */}
      {evaluation.vocabularySuggestions && evaluation.vocabularySuggestions.length > 0 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-100 shadow-xs">
          <div className="flex items-center gap-2 mb-5">
            <BookOpen className="w-5 h-5 text-indigo-600" />
            <h3 className="font-extrabold text-base sm:text-lg text-slate-900">
              Vocabulary You Could Improve (Band 8+ Upgrades)
            </h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {evaluation.vocabularySuggestions.map((v, idx) => (
              <div
                key={idx}
                className="p-4 rounded-2xl bg-slate-50 border border-slate-200/70 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-xs text-slate-400 line-through">"{v.term}"</span>
                    <span className="text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-indigo-100 text-indigo-700">
                      Upgrade
                    </span>
                  </div>
                  <p className="text-sm font-extrabold text-indigo-950">
                    {v.advancedAlternative}
                  </p>
                  <p className="text-xs text-slate-600 italic mt-2 bg-white p-2 rounded-xl border border-slate-100">
                    "{v.example}"
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* BETTER WAYS TO EXPRESS SENTENCES (BEFORE & AFTER) */}
      {evaluation.betterExpressions && evaluation.betterExpressions.length > 0 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-100 shadow-xs">
          <div className="flex items-center gap-2 mb-5">
            <Sparkles className="w-5 h-5 text-pink-600" />
            <h3 className="font-extrabold text-base sm:text-lg text-slate-900">
              Better & More Natural Ways to Express Your Ideas
            </h3>
          </div>

          <div className="space-y-3">
            {evaluation.betterExpressions.map((exp, idx) => (
              <div
                key={idx}
                className="p-4.5 rounded-2xl bg-gradient-to-r from-pink-50/50 via-purple-50/50 to-indigo-50/50 border border-indigo-100 space-y-2"
              >
                <div className="flex items-start gap-2">
                  <span className="text-xs font-bold text-slate-400 shrink-0 mt-0.5">Original:</span>
                  <p className="text-xs sm:text-sm text-slate-600 italic">
                    "{exp.original}"
                  </p>
                </div>
                <div className="flex items-start gap-2">
                  <span className="text-xs font-extrabold text-indigo-700 shrink-0 mt-0.5">Native / Band 8+:</span>
                  <p className="text-xs sm:text-sm font-bold text-indigo-950">
                    "{exp.refined}"
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* PRONUNCIATION COACHING */}
      {evaluation.pronunciationFeedback && evaluation.pronunciationFeedback.length > 0 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-100 shadow-xs">
          <div className="flex items-center gap-2 mb-4">
            <Volume2 className="w-5 h-5 text-amber-500" />
            <h3 className="font-extrabold text-base sm:text-lg text-slate-900">
              Pronunciation Areas to Practice
            </h3>
          </div>

          <ul className="space-y-2.5">
            {evaluation.pronunciationFeedback.map((p, idx) => (
              <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700 leading-relaxed">
                <span className="w-2 h-2 rounded-full bg-amber-400 mt-2 shrink-0" />
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* NEXT PRACTICE RECOMMENDATION */}
      <div className="bg-gradient-to-r from-indigo-50 via-purple-50 to-pink-50 rounded-3xl p-6 sm:p-8 border border-indigo-100">
        <div className="flex items-center gap-2 mb-2 text-indigo-900">
          <Lightbulb className="w-5 h-5 text-indigo-600" />
          <h3 className="font-extrabold text-base sm:text-lg">
            Recommendation for Your Next Practice Session
          </h3>
        </div>
        <p className="text-sm sm:text-base text-slate-800 leading-relaxed mt-2 font-medium">
          {evaluation.nextPracticeRecommendation}
        </p>
      </div>

      {/* USER'S RECORDED TRANSCRIPT ACCORDION */}
      <div className="bg-white rounded-3xl p-6 border border-slate-100 shadow-xs">
        <h4 className="font-bold text-slate-800 text-sm mb-2 flex items-center gap-2">
          <FileText className="w-4 h-4 text-slate-500" />
          Full Transcript of Your Response
        </h4>
        <p className="text-xs sm:text-sm text-slate-600 leading-relaxed bg-slate-50 p-4 rounded-2xl border border-slate-200/60 font-mono">
          "{session.transcript}"
        </p>
      </div>

      {/* ACTION BUTTONS */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-200">
        <button
          id="eval-dashboard-btn"
          onClick={onBackToDashboard}
          className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-3 rounded-2xl bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 font-bold text-sm transition-colors cursor-pointer"
        >
          <LayoutDashboard className="w-4 h-4" />
          <span>Back to Dashboard</span>
        </button>

        <div className="flex items-center gap-3 w-full sm:w-auto">
          <button
            id="eval-view-progress-btn"
            onClick={onViewProgress}
            className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-2 px-5 py-3 rounded-2xl bg-indigo-50 hover:bg-indigo-100 text-indigo-700 font-bold text-sm transition-colors cursor-pointer"
          >
            <TrendingUp className="w-4 h-4" />
            <span>View Progress</span>
          </button>

          <button
            id="eval-practice-again-btn"
            onClick={onPracticeAgain}
            className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-2 px-6 py-3 rounded-2xl bg-gradient-to-r from-blue-600 via-indigo-600 to-pink-500 hover:from-blue-700 hover:via-indigo-700 hover:to-pink-600 text-white font-extrabold text-sm shadow-md shadow-indigo-200 active:scale-98 transition-all cursor-pointer"
          >
            <RefreshCw className="w-4 h-4" />
            <span>Practice Another Question</span>
          </button>
        </div>
      </div>
    </div>
  );
};
